/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWebhookRouteImport } from './routes/api/webhook'
import { Route as ApiStateRouteImport } from './routes/api/state'
import { Route as ApiWebhookTestRouteImport } from './routes/api/webhook/test'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhookRoute = ApiWebhookRouteImport.update({
  id: '/api/webhook',
  path: '/api/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStateRoute = ApiStateRouteImport.update({
  id: '/api/state',
  path: '/api/state',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhookTestRoute = ApiWebhookTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => ApiWebhookRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/api/state': typeof ApiStateRoute
  '/api/webhook': typeof ApiWebhookRouteWithChildren
  '/api/webhook/test': typeof ApiWebhookTestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/api/state': typeof ApiStateRoute
  '/api/webhook': typeof ApiWebhookRouteWithChildren
  '/api/webhook/test': typeof ApiWebhookTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/api/state': typeof ApiStateRoute
  '/api/webhook': typeof ApiWebhookRouteWithChildren
  '/api/webhook/test': typeof ApiWebhookTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/logout'
    | '/api/state'
    | '/api/webhook'
    | '/api/webhook/test'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/logout'
    | '/api/state'
    | '/api/webhook'
    | '/api/webhook/test'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/logout'
    | '/api/state'
    | '/api/webhook'
    | '/api/webhook/test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  ApiStateRoute: typeof ApiStateRoute
  ApiWebhookRoute: typeof ApiWebhookRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhook': {
      id: '/api/webhook'
      path: '/api/webhook'
      fullPath: '/api/webhook'
      preLoaderRoute: typeof ApiWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/state': {
      id: '/api/state'
      path: '/api/state'
      fullPath: '/api/state'
      preLoaderRoute: typeof ApiStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhook/test': {
      id: '/api/webhook/test'
      path: '/test'
      fullPath: '/api/webhook/test'
      preLoaderRoute: typeof ApiWebhookTestRouteImport
      parentRoute: typeof ApiWebhookRoute
    }
  }
}

interface ApiWebhookRouteChildren {
  ApiWebhookTestRoute: typeof ApiWebhookTestRoute
}

const ApiWebhookRouteChildren: ApiWebhookRouteChildren = {
  ApiWebhookTestRoute: ApiWebhookTestRoute,
}

const ApiWebhookRouteWithChildren = ApiWebhookRoute._addFileChildren(
  ApiWebhookRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  ApiStateRoute: ApiStateRoute,
  ApiWebhookRoute: ApiWebhookRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
